FROM nginx:latest
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY . /www/data

RUN { \
      echo 'client_max_body_size 0;'; \
    } > /etc/nginx/conf.d/unrestricted_client_body_size.conf
