version: '3.8'
services:
    ecogesweb:
        image: ecogesweb
        build:
            context: .
            dockerfile: Dockerfile.ecoges
        environment:
            - PORT=8004
        env_file:
            - .env
        expose:
            - 8004
        networks:
            - nginx-proxy
        volumes:
            - static_ecoges:/home/yllorca/dockerdir/ecogesweb/static_cdn/
            - media_ecoges:/home/yllorca/dockerdir/ecogesweb/media_cdn/
        restart: always
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.ecoges-nginx
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=www.ecogestionambiental.cl # Environment variable needed for nginx proxy
            - LETSENCRYPT_HOST=www.ecogestionambiental.cl # Environment variables needed for Let's Encrypt companion
            - LETSENCRYPT_EMAIL=yllorca@helloworld.cl
        networks:
         - nginx-proxy # Connect this container to network named nginx-proxy, that will be described below
        restart: always
        depends_on:
            - ecogesweb
        volumes:
            - static_ecoges:/home/yllorca/dockerdir/ecogesweb/static_cdn/
    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy:alpine
        restart: "always" # Always restart container
        ports:
            - "80:80" # Port mappings in format host:container
            - "443:443"
        networks:
            - nginx-proxy # Name of the network these two containers will share
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" # Label needed for Let's Encrypt companion container
        volumes: # Volumes needed for container to configure proixes and access certificates genereated by Let's Encrypt companion container
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - "nginx-conf:/etc/nginx/conf.d"
            - "nginx-vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "certs:/etc/nginx/certs:ro"
            - "./custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf"
    letsencrypt:
        container_name: letsencrypt
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "nginx-conf:/etc/nginx/conf.d"
            - "nginx-vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "certs:/etc/nginx/certs:rw"
        depends_on: # Make sure we start nginx proxy container first
            - nginx-proxy
    docker-db:
      container_name: docker-db
      image: postgres:9.6
      restart: always
      ports:
        - "5432:5432"
      networks:
        - nginx-proxy
      env_file: ./.env-db
      volumes:
        - ./db/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
        - postgres_data:/var/lib/postgresql/data/

networks:
    nginx-proxy:
            name: proxy_nginx-proxy
volumes:
    static_ecoges:
        external: true
    media_ecoges:
        external: true
    nginx-conf:
    nginx-vhost:
    html:
    certs:
